djangoBango/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetView
from django.urls import path, include

from djangoBango import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('user.urls', namespace='user')),
    path('user/', include([
        # password reset functionality
        path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'),
             name='password-reset'),
        path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
             name='password_reset_done'),
        path('password-reset-confirm/<uidb64>/<token>/',
             PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
             name='password_reset_confirm'),
        path('password-reset-complete/',
             PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
             name='password_reset_complete'),
    ])),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import console_view, redirect_view

app_name = 'home'
urlpatterns = [
    path('', redirect_view, name='redirect'),
    path('home/', console_view, name='home')
]

user/urls.py
from django.urls import path, include
from user.views import login_view, logout_view, signup_view, customer_details_view, update_customer_view, \
    delete_customer_view, update_user_view, update_customer_profile_view, my_profile_view, password_change_view, \
    my_profile_update_view

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('customer_details/<str:customer_guid>', customer_details_view, name='customer_details'),
    path('customer_info/update/<str:customer_guid>', update_customer_view, name='customer_update'),
    path('customer/user_info/update/<str:customer_guid>', update_user_view, name='user_update'),
    path('customer/update/<str:customer_guid>', update_customer_profile_view, name='customer_profile_update'),
    path('my_profile/', my_profile_view, name='my_profile'),
    path('my_profile/update/', my_profile_update_view, name='my_profile_update'),
    path('change_password/', password_change_view, name='password_change'),
    path('customer/delete/<str:customer_guid>', delete_customer_view, name='customer_delete'),
]

templates/includes/error.html
{% if messages %}
    <div class="toast-container position-fixed top-0 end-0 p-3" style="z-index: 11">
        {% for message in messages %}
            <div class="toast show align-items-center text-white {% if 'success' in message.tags %}bg-success{% elif 'error' in message.tags %}bg-danger{% elif 'info' in message.tags %}bg-info{% elif 'warning' in message.tags %}bg-warning{% endif %}" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/includes/header.html
<style>
    a {
        font-size: 14px;
        font-weight: 700
    }

    .superNav {
        font-size: 13px;
    }

    .form-control {
        outline: none !important;
        box-shadow: none !important;
    }

    @media screen and (max-width: 540px) {
        .centerOnMobile {
            text-align: center
        }
    }
</style>
<div class="superNav border-bottom py-2 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
                <select class="me-3 border-0 bg-light">
                    <option value="en-us">EN-US</option>
                </select>
                <span class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"><strong>nishad@marvelous-tech.com</strong></span>
                <span class="me-3"><i
                        class="fa-solid fa-phone me-1 text-warning"></i> <strong>1-800-123-1234</strong></span>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-none d-lg-block d-md-block-d-sm-block d-xs-none text-end">
                <span class="me-3"><i class="fa-solid fa-address-book text-muted me-1"></i><a class="text-muted" href="#">Contact</a></span>
                <span class="me-3"><i class="fa-solid fa-file  text-muted me-2"></i><a class="text-muted" href="#">Policy</a></span>
            </div>
        </div>
    </div>
</div>

templates/includes/navbar.html
<nav id="navbar_top" class="navbar navbar-expand-lg bg-body-tertiary shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">Django Bango</a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse me-75" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
            </ul>
            <div class="d-flex align-items-center justify-content-start">

                <div class="dropdown">
                    <a
                            class="nav-link dropdown-toggle"
                            href="#"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                    >
                        <img src="https://ui-avatars.com/api/?name={{ user.username }}&bold=true&background=036ffc&color=ffffff"
                             class="rounded-circle" height="25"
                             alt="User Avatar" loading="lazy"/>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item n_l" href="{% url 'user:my_profile' %}"><span
                                class="bi bi-person-circle">Profile</span></a></li>
                        <li><a class="dropdown-item n_l" href="{% url 'user:password_change' %}"><span
                                class="bi bi-shield-lock">Change Password</span></a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item n_l" href="{% url 'user:logout' %}"><span
                                class="bi bi-box-arrow-left">Logout</span></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</nav>